### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by abc2005** [jeppeman/android-jetpack-playground#1]
well done buddy , perfect , I just enjoyed it all 
a question , I'm really a android lover ,i'm coding for 4 years and I've made lots of application . 

so I get familiar with jetpack and android architecture components and want to learn it . 

what do you suggest ? where I should begin to study and begin to use them ?

thanks anyway

**Comment by jeppeman** [comment]
Hi there, thanks! Go through some of the official resources [here](https://developer.android.com/jetpack/), pick a field you're interested in and apply them to some hobby project you have.
